version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
    importas:
      no-unaliased: false
      no-extra-aliases: true
      alias:
      - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/apis/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/(\w+)/(\w+)
        alias: $1$2
      - pkg: github.com/openshift/api/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
      - pkg: sigs.k8s.io/controller-runtime/pkg/log
        alias: logf
      - pkg: k8s.io/client-go/kubernetes/scheme
        alias: clientgoscheme
    goimports:
      local-prefixes: github.com/opdev/docling-operator

  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
