apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: docling-operator
    app.kubernetes.io/managed-by: kustomize
  name: docling-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: docling-role
subjects:
- kind: ServiceAccount
  name: docling-sa
  namespace: system
